version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_USER: grafana
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
      GF_DATABASE_SSL_MODE: disable
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./data/grafana:/var/lib/grafana